#!/bin/bash
#
# resmon       Starts resmon.
#
#
# chkconfig: 2345 99 01
# description: resmon is a systems monitoring facility to aid nagios \
# checks.  it should always be running when the system is in operation.
### BEGIN INIT INFO
# Provides: $resmon
### END INIT INFO

# Source function library.
. /etc/init.d/functions

RESMON_DIR=/opt/resmon
RESMON_CONF=$RESMON_DIR/resmon.conf
RESMON_BIN=$RESMON_DIR/resmon
RESMON_LOCK=/var/lock/subsys/resmon

[ -f $RESMON_BIN ] || exit 0
[ -f $RESMON_CONF ] || exit 0

RETVAL=0

umask 077

start() {
        echo -n $"Starting resmon: "
        daemon $RESMON_BIN
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $RESMON_LOCK
        return $RETVAL
}
stop() {
        echo -n $"Shutting down resmon: "
        killproc $RESMON_BIN
        echo
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f $RESMON_LOCK
        return $RETVAL
}
rhstatus() {
        status resmon
}
restart() {
        stop
        start
}
reload() {
        echo -n $"Reloading resmon: "
        killproc $RESMON_BIN -HUP
        echo
        return $?
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        rhstatus
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  condrestart)
        [ -f $RESMON_LOCK ] && restart || :
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        exit 1
esac

exit $?

